### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by cs136** [cs136/seashell#602] opened 2017-01-05 18:38 UTC
Submitter: Chase Haddleton
Email: wchaddle@uwaterloo.ca
Error on deleting file. 

version:     3.0.0 (stable at a43e3a2)
api_version: 7
host:        ubuntu1404-010.hosts.seashell.student.cs.uwaterloo.ca
error:       Bad argument: build-path: contract violation
  expected: (or/c path-for-some-system? path-string? 'up 'same)
  given: 'relative
  argument position: 2nd
  other arguments...:
   #<path:/u1/wchaddleton/.seashell/projects/A0>.

Ultimately, the file is indeed deleted, but this error message does show up to the user.

Also, this form uses an poor captcha, consider using Google's new reCaptcha - it's free!

**Comment by e45lee** [comment] 2017-01-10 02:44
Duplicate of #600.

**Closed by e45lee** 2017-01-10 02:44 UTC
Labels: duplicate
