### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by cs136** [cs136/seashell#505] opened 2016-02-25 22:15 UTC
Submitter: David Briggs (20616231)
Email: dpbriggs@uwaterloo.ca
More of a feature request:

Given the bugginess of the emacs keybindings, I tried to use the browser extention Edit WIth Emacs (https://chrome.google.com/webstore/detail/edit-with-emacs/ljobjlafonikaiipfkggjbhkghgicgoh?hl=en) .

It allows you to write in chrome text areas within emacs. It seems to work for other programming online websites, but it doesn't for seashell.

Thanks for reading this!

David

**Comment by e45lee** [comment] 2016-05-10 10:45
Duplicate of #377

**Closed by e45lee** 2016-05-10 10:45 UTC
Labels: enhancement, gitreports-uncategorized, low-priority
