### ISSUE TITLE
Auto load most recently worked on file in a question

### ISSUE THREAD

**Issue by zanwenhuahao** [cs136/seashell#180] opened 2015-02-17 18:46 UTC
When clicking on question for an assignment, the most recently worked on question does not automatically load. It is blank underneath the menu bar, this is a little frustrating as I have to look through (and if the question had multiple files) the files to find which one I was working on just before (and sometimes people don't pay attention to the name of the file they were working on). Could we have this feature back please?

**Comment by e45lee** [comment] 2015-02-17 20:47
This is a duplicate of #79

**Closed by e45lee** 2015-02-17 20:47 UTC
Labels: duplicate
